name: FallenDisks
version: 0.3.2
main: cc.fallenrealms.falldisks.FallenDisksPlugin
api-version: '1.21'
author: Bipolar
description: Custom music disks + jukebox playlists + speaker relays + portable jukeboxes.
commands:
  fdisks:
    description: FallenDisks main command.
    usage: /fdisks
permissions:
  fallendisks.*:
    description: Grants access to all FallenDisks permissions.
    default: op
    children:
      fallendisks.create: true
      fallendisks.replace: true
      fallendisks.delete: true
      fallendisks.give: true
      fallendisks.givespeaker: true
      fallendisks.list: true
      fallendisks.admin: true
      fallendisks.reload: true
      fallendisks.create.nolimit: true
      fallendisks.pack.bypass: true
      fallendisks.pack.force.lan: true
      fallendisks.pack.force.public: true

  fallendisks.create:
    description: Allows creating new custom disks.
    default: op
  fallendisks.replace:
    description: Allows replacing an existing disk's audio/metadata.
    default: op
  fallendisks.delete:
    description: Allows deleting disks.
    default: op
  fallendisks.give:
    description: Allows giving disks to players.
    default: op
  fallendisks.list:
    description: Allows listing disks.
    default: true
  fallendisks.admin:
    description: Allows admin-only functions (e.g., resend pack in standalone mode).
    default: op
  fallendisks.reload:
    description: Allows reloading the plugin config.
    default: op
  fallendisks.create.nolimit:
    description: Bypasses max length limits when creating/replacing disks.
    default: op
  fallendisks.pack.bypass:
    description: Bypasses automatic pack prompting (standalone mode only).
    default: op
  fallendisks.pack.force.lan:
    description: Forces a player to use the LAN pack URL (standalone mode only).
    default: op
  fallendisks.pack.force.public:
    description: Forces a player to use the Public pack URL (standalone mode only).
    default: op
